import Stack from "@mui/material/Stack";
import Box from "@mui/material/Box";
import Skeleton from "@mui/material/Skeleton";

export default function ApiAccessPlaceholder() {
  return (
    <Stack
      gap={2}
      p={{ xs: "16px 24px", md: "48px" }}
    >
      <Skeleton
        variant="text"
        width="250px"
        height="30px"
      />
      <Box>
        <Stack
          direction={"row"}
          justifyContent={"space-between"}
          alignItems={"center"}
          gap={1}
          py="8px"
        >
          <Skeleton
            variant="text"
            width="150px"
            height="20px"
          />
          <Skeleton
            variant="text"
            width="150px"
            height="20px"
          />
        </Stack>
        <Stack
          overflow={"auto"}
          sx={{ width: "100%", height: "137px" }}
          boxSizing={"border-box"}
          bgcolor={"#F5F3F7"}
          borderRadius={"24px"}
          padding={2}
        >
          <Skeleton
            variant="text"
            width="150px"
            height="20px"
          />
          <Skeleton
            variant="text"
            width="350px"
            height="20px"
          />
          <Skeleton
            variant="text"
            width="250px"
            height="20px"
          />
          <Skeleton
            variant="text"
            width="150px"
            height="20px"
          />
          <Skeleton
            variant="text"
            width="250px"
            height="20px"
          />
        </Stack>
      </Box>

      <Box>
        <Stack
          direction={"row"}
          justifyContent={"space-between"}
          alignItems={"center"}
          gap={1}
          py="8px"
          height={"77px"}
        >
          <Skeleton
            variant="text"
            width="150px"
            height="20px"
          />
          <Skeleton
            variant="text"
            width="150px"
            height="20px"
          />
        </Stack>
        <Stack
          overflow={"auto"}
          sx={{ width: "100%", height: "137px" }}
          boxSizing={"border-box"}
          bgcolor={"#F5F3F7"}
          borderRadius={"24px"}
          padding={2}
        >
          {" "}
          <Skeleton
            variant="text"
            width="10px"
            height="20px"
          />
          <Skeleton
            variant="text"
            width="150px"
            height="20px"
          />
          <Skeleton
            variant="text"
            width="10px"
            height="20px"
          />
        </Stack>
      </Box>

      <Box>
        <Stack
          direction={"row"}
          justifyContent={"space-between"}
          alignItems={"center"}
          gap={1}
          py="8px"
        >
          <Skeleton
            variant="text"
            width="150px"
            height="20px"
          />
          <Skeleton
            variant="text"
            width="150px"
            height="20px"
          />
        </Stack>
        <Stack
          overflow={"auto"}
          sx={{ maxWidth: "100vw", width: "100%" }}
          boxSizing={"border-box"}
          bgcolor={"#F5F3F7"}
          borderRadius={"24px"}
          padding={2}
        >
          <Skeleton
            variant="text"
            width="150px"
            height="20px"
          />
          <Skeleton
            variant="text"
            width="350px"
            height="20px"
          />
          <Skeleton
            variant="text"
            width="250px"
            height="20px"
          />
          <Skeleton
            variant="text"
            width="350px"
            height="20px"
          />
          <Skeleton
            variant="text"
            width="150px"
            height="20px"
          />
        </Stack>
      </Box>
    </Stack>
  );
}
