name: Lint and build current commit

on:
  pull_request:
    branches-ignore:
      - staging
      - main
    types:
      - opened
      - reopened

jobs:
  linter-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run linting
        run: yarn lint

      - name: Build the project
        run: yarn build
